#cloud-config
# spam4kev@gmail.com 2/6/16
yum_repos:
   WANdiscoSVN:
      baseurl: http://opensource.wandisco.com/centos/7/svn-1.9/RPMS/$basearch/
      enabled: true
      gpgcheck: true
      gpgkey: http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco
      name: WANdisco SVN Repo 1.9

users:
  - default
  - name: fitzhenk
    gecos: kev
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh-import-id: None
    lock-passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRKqdKKEuOCc+h+oagKolmH11AOrODDCCYBqgWz0ouVr2FTNelevM3J2e+ym/prE4Js/5yOyUPwz23LgiSEM5JNnGhJPSgpIU7NwybNDHe7q7Xa5aRoIoJ+d7ls21Kp0ZUnQxroTM0NOl/5hv1i0HHI8/WtMLNCbOqoGJQIfOO6mqRTxWtCpXzskPeL7R8HAM0wty+HJ+aF3B/RBJKHWpU6m5t1LXuiqDLlCtFUfFp20E9SJbTkf9+kiX5XlTSRcOkex0OTyiK/jfVIRKuyytZPP7/BV/Hvy1DyIcgRLyoKRPuuLwpp9elcE4CHLp1TnCwR6XkBrrZAlcZdddozTWB imported-openssh-key

runcmd:
 - dhclient
 - yum update -y
 - yum install -y tar wget which
 - wget http://www.apache.org/dist/mesos/0.27.0/mesos-0.27.0.tar.gz
 - tar -zxf mesos-0.27.0.tar.gz
 - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo 
 - yum install -y epel-release
 - yum update systemd
 - yum groupinstall -y "Development Tools"
 - yum install -y apache-maven python-devel java-1.8.0-openjdk-devel zlib-devel libcurl-devel openssl-devel cyrus-sasl-devel cyrus-sasl-md5 apr-devel subversion-devel apr-util-devel
 - cd mesos
 - ./bootstrap
 - mkdir build
 - cd build
 - ../configure
 - make
 - make check
