#cloud-config
# spam4kev@gmail.com 2/6/16
# -This config expects the mesos cluster hosts to be named mesos-1, mesos-2,
# mesos-3, ..., and will set mesos-1 to be the master
# -It assumes your master will have the public ip 10.11.11.156 associated. Find the IP below and change it with your public IP (EIP) 

users:
  - default
  - name: spam4kev
    gecos: kev
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh-import-id: None
    lock-passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRKqdKKEuOCc+h+oagKolmH11AOrODDCCYBqgWz0ouVr2FTNelevM3J2e+ym/prE4Js/5yOyUPwz23LgiSEM5JNnGhJPSgpIU7NwybNDHe7q7Xa5aRoIoJ+d7ls21Kp0ZUnQxroTM0NOl/5hv1i0HHI8/WtMLNCbOqoGJQIfOO6mqRTxWtCpXzskPeL7R8HAM0wty+HJ+aF3B/RBJKHWpU6m5t1LXuiqDLlCtFUfFp20E9SJbTkf9+kiX5XlTSRcOkex0OTyiK/jfVIRKuyytZPP7/BV/Hvy1DyIcgRLyoKRPuuLwpp9elcE4CHLp1TnCwR6XkBrrZAlcZdddozTWB imported-openssh-key

runcmd:
 - dhclient
 - yum update -y
 - rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
 - eth0_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4/)
 - echo "$eth0_ip $(hostname)" >> /etc/hosts
 - echo "10.11.11.156 mesos-master" >> /etc/hosts
 - yum -y install http://downloads.mesosphere.io/master/centos/7/mesos-0.27.0-0.2.190.centos701406.x86_64.rpm marathon mesosphere-zookeeper
 - firewall-offline-cmd --add-port=5050/tcp
 - yum install -y epel-release
 - curl https://raw.githubusercontent.com/spam4kev/mesos/master/startup.sh -o startup.sh
